### ISSUE TITLE
ExampleDecoder doesn't encode strings as expected

### ISSUE THREAD

**Issue by alaiacano** [spotify/spotify-tensorflow#102]
I have an Example that contains a bunch of `bytes_list` values. I dropped a debugger in [this function](https://github.com/spotify/spotify-tensorflow/blob/d2f093d355a2caa67c1e1566b6b50f4fe4d478f9/spotify_tensorflow/example_decoders.py#L29-L40) and inspected the data.

Looking at the example `ex`, I see

```
feature {
    key: "genres"
    value {
      bytes_list {
        value: "country"
        value: "modern country rock"
      }
    }
  }
```

Looking at it after `MessageToJson`, and also what prints to the console when using `tfr-read`, I see:

```
      "microgenre_affinity.genres": {
        "bytesList": {
          "value": [
            "Y291bnRyeQ==",
            "bW9kZXJuIGNvdW50cnkgcm9jaw==",
          ]
```

**Comment by brianmartin** [comment]
Hm, this is quite unfortunate. To summarize some of the internal conversation: because the `Feature` proto does not have a string type there is no way for `MessageToJson` to distinguish arbitrary bytes from bytes of a string.

We can verify this by digging into the protobuf implementation where we can see that it is transforming any bytes value into a `base64`-encoded UTF-8 string. [[code](https://github.com/protocolbuffers/protobuf/blob/1484b580560397ac544660be7a2e8bf81ab56199/python/google/protobuf/json_format.py#L276-L278
)]

And we can verify that with your example values:

```
$ echo -n 'Y291bnRyeQ==' | base64 -D && echo
country
$ echo -n 'bW9kZXJuIGNvdW50cnkgcm9jaw==' | base64 -D && echo
modern country rock
```

**Comment by andrewsmartin** [comment]
Seems like it will be difficult to come up with a general solution since as you say @brianmartin, there's no way to differentiate between strings from arbitrary bytes. Seems easy enough for the user to do the base64 decoding afterwards - should we close this? cc @alaiacano
